- name: installing nginx
  hosts: local
  connection: local
  tasks:
    - name: install nginx
      ansible.builtin.dnf:
        name: nginx
        state: installed

    - name: start and enable nginx
      ansible.builtin.service:
          name: nginx
          enabled: yes
          state: restarted
