- name: variables
  hosts: local
  connection: local
  vars_files:
    - project.yaml

  tasks:
    - name: printing data in var_files
      ansible.builtin.debug:
        msg: "Project is {{ PROJECT }} Environment is {{ ENVIRONMENT }}"  